repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
    - id: ruff
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
-   repo: local
    hooks:
    -   id: poetry-build
        name: Poetry Build
        entry: poetry build
        language: system
        pass_filenames: false
        always_run: true