[project]
name = "dealsteal"
version = "0.1.0"
description = "e-commerce deal hunter"
authors = [{name = "Tomas Timinskas", email = "tatiminskas@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "Babel>=2.15.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.0.285",
    "isort>=5.12.0",
    "black>=23.7.0",
    "pytest>=8.2.2",
]
notebooks = [
    "ipykernel>=6.29.5",
    "pickleshare>=0.7.5",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
dealsteal = "dealsteal.runner:main"

[tool.ruff]
line-length = 88
target-version = "py311"

select = ["E", "F", "W", "I", "UP", "B", "SIM", "RUF"]
ignore = ["E501", "B008", "I001", "RUF012", "RUF100"]

[tool.ruff.flake8-quotes]
docstring-quotes = 'double'
inline-quotes = 'double'
multiline-quotes = 'double'

[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort] # Making isort compatible with black
profile = 'black'
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[tool.pytest.ini_options]
testpaths = ["src/tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
pythonpath = [
  "src",
  "."
]
